In [2]:
def my_function():
    pass
    # your code here

In [3]:
def my_sq(x):
    return x ** 2

In [5]:
my_sq(4)

16

In [6]:
my_sq("hello")

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [8]:
"hello" * 2

'hellohello'

In [9]:
def my_sq(x: int|float) -> int|float:
    return x ** 2

In [10]:
my_sq("hello")

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [11]:
assert my_sq(4) == 16

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame({
    "a": [10, 20, 30],
    "b": [20, 30, 40]
})

In [15]:
df["a"] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [16]:
df.a ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [17]:
my_sq(df.a)

0    100
1    400
2    900
Name: a, dtype: int64

In [19]:
type(df["a"])

pandas.core.series.Series

In [20]:
df["a"].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [21]:
my_sq

<function __main__.my_sq(x: int | float) -> int | float>

In [22]:
my_sq()

TypeError: my_sq() missing 1 required positional argument: 'x'

In [23]:
def my_exp(x, e):
    return x ** e

In [24]:
my_exp(4, 2)

16

In [25]:
my_exp(2, 10)

1024

In [28]:
df["a"].apply(my_exp)

TypeError: my_exp() missing 1 required positional argument: 'e'

In [29]:
my_exp(4)

TypeError: my_exp() missing 1 required positional argument: 'e'

In [30]:
df["a"].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [32]:
def my_exp_flipped(e, x):
    return my_exp(x, e)

In [34]:
my_exp_flipped(10, 2)

1024

In [35]:
df["a"].apply(my_exp_flipped, x=2)

0          1024
1       1048576
2    1073741824
Name: a, dtype: int64

In [36]:
df["a"].apply(lambda val: my_exp(x=val, e=10))

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [37]:
df["a"].apply(lambda val: my_exp(x=2, e=val))

0          1024
1       1048576
2    1073741824
Name: a, dtype: int64

In [38]:
df

a   b
0  10  20
1  20  30
2  30  40

In [39]:
def print_me(x):
    print(x)

In [40]:
print_me("hello")

hello


In [42]:
x = print_me("hello")
x

hello


In [43]:
x

In [44]:
df.a.apply(print_me)

10
20
30


0    None
1    None
2    None
Name: a, dtype: object

In [45]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [46]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [49]:
assert avg_3(0, 5, 10) == 5

In [50]:
df.apply(avg_3)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [51]:
avg_3(0)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [52]:
def avg_3_apply(col):
    return col.mean()

In [53]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [56]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [57]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [60]:
df

a   b
0  10  20
1  20  30
2  30  40

In [62]:
df.apply(print_me, axis="columns")

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64
a    30
b    40
Name: 2, dtype: int64


0    None
1    None
2    None
dtype: object

In [63]:
df.apply(print_me, axis=1)

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64
a    30
b    40
Name: 2, dtype: int64


0    None
1    None
2    None
dtype: object

In [64]:
df

a   b
0  10  20
1  20  30
2  30  40

In [66]:
(df.a + df.b) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [67]:
def avg_2(x, y):
    return (x + y) / 2

In [68]:
avg_2(df.a, df.b)

0    15.0
1    25.0
2    35.0
dtype: float64

In [75]:
import numpy as np

def avg_2_mod(x, y):
    if (x == 20):
        return np.nan
    else:
        return (x + y) / 2

In [74]:
np.__version__

'2.0.0'

In [76]:
avg_2_mod(20, 10)

nan

In [77]:
avg_2_mod(0, 10)

5.0

In [78]:
avg_2_mod(df.a, df.b)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [80]:
df.a == 20

0    False
1     True
2    False
Name: a, dtype: bool

In [82]:
(df.a == 20).any()

np.True_

In [83]:
(df.a == 20).all()

np.False_

In [84]:
avg_2_mod(20, 10)

nan

In [85]:
import numpy as np

def avg_2_mod(x, y):
    if (x == 20):
        return np.nan
    else:
        return (x + y) / 2

avg_2_mod_np = np.vectorize(avg_2_mod)

In [87]:
avg_2_mod_np(20, 10)

array(nan)

In [88]:
avg_2_mod_np(0, 10)

array(5.)

In [89]:
avg_2_mod_np(df.a, df.b)

array([15., nan, 35.])

In [91]:
@np.vectorize
def avg_2_mod_np(x, y):
    if (x == 20):
        return np.nan
    else:
        return (x + y) / 2

In [92]:
avg_2_mod_np(df.a, df.b)

array([15., nan, 35.])

In [93]:
avg_2_mod_np(0, 10)

array(5.)

In [95]:
import numba

In [96]:
@numba.vectorize
def avg_2_mod_numba(x, y):
    if (x == 20):
        return np.nan
    else:
        return (x + y) / 2

In [97]:
avg_2_mod_numba(10, 20)

np.float64(15.0)

In [98]:
avg_2_mod_numba(df.a, df.b)

0    15.0
1     NaN
2    35.0
dtype: float64

In [99]:
avg_2_mod_numba(df.a.values, df.b.values)

array([15., nan, 35.])

In [100]:
%%timeit
avg_2(df.a, df.b)

42.6 μs ± 4.07 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [101]:
%%timeit
avg_2_mod_np(df.a, df.b)

27.9 μs ± 141 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [103]:
%%timeit
avg_2_mod_numba(df.a.values, df.b.values)

5.99 μs ± 105 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [104]:
%%timeit
avg_2_mod_numba(df.a, df.b)

45 μs ± 5.21 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
